### ISSUE TITLE
Fluid examples: tests don't run on Linux

### ISSUE THREAD

**Issue by mattetti** [microsoft/FluidExamples#36]
On Linux:

```
git clone https://github.com/microsoft/FluidExamples.git
cd into any example
run start test
```

` npm run test` fails on Linux/WSL ~/Code/fluid-projects/FluidExamples/brainstorm/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory

**Comment by skylerjokiel** [comment]
Closing this old issue.
